### ISSUE TITLE
add subwork discount code on first page 

### ISSUE THREAD

**Issue by yangwao** [kodadot/subwork#137]
on very first page I would add reward for those who scrolled very bottom to claim subwork shirt, like $50 voucher for first 30 claims 

- [ ] when there will be SubWork design up in shop 
- https://github.com/kodadot/ops-internal/issues/696

**Comment by JustLuuuu** [comment]
Ref:
- https://github.com/kodadot/ops-internal/issues/710

Your coupon code is ready: **SUBWRKDRP** Till 1.of September - 30 claims for now. Only on Subwork shirt
<img width="1124" alt="Screenshot 2023-07-21 at 14 53 48" src="https://github.com/kodadot/subwork/assets/104380776/9a371b6a-8fa1-42ff-85f6-402b373af829">

**Comment by yangwao** [comment]
Maybe someone is looking here too!
- 2d17a54..c2ac55a
