### ISSUE TITLE
Accommodation

### ISSUE THREAD

**Issue by FrankBevr** [kodadot/subwork#166]
### Hola

there was a discussion on sub0 about a accomadation which is maybe available in November.

any news about accommodation, which i should be aware of?

Just rushed thruh my head, so i drop a issue.

### Cheers, greetings to Berry 🐶

*P.s. I sadly missed to hop by in the summer. November and December is still on my list.*

**Comment by yangwao** [comment]
Been thinking of making some bounty which would cover hacker house 👀

> https://docs.google.com/document/d/1vMSF7GFAGyVshFD-Ms0BlaF6AZCl9zsYQgx6BxQRQsc/edit?pli=1
> cmd+a
> cmd+c
> cmd+n
> subwork hacker house for month
> cmd+v

wyt :D

**Comment by FrankBevr** [comment]
@yangwao 

I'm not sure if i arrive in the next days. 

But most likely i will be in Istanbul. 
I still have in my head, that we can scratch something out if a spot is available in the team. 
If not I do ehh web3ar bag or something.
And If you are not in Istanbul then cia in Hungary. 
Or see ya in the upcomming days, i don't know. 

**Just wanna drop a message.** 

> I lost my key to my TG again, will take a bit till i get it back. Thats Why i drop something here. 
> #missUsingGitHub

Greeting to everyone 🎩
