### ISSUE TITLE
Swarm event in SubWork - June

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/subwork#171]
## Event details:
- June, from 17-23.6
- 4 days of closer team "hackaton" + 3 days of open to the public summit w presentations, panels and demos, online/IRL combo.

## Contact person on TG:
- gasper93
- Mina_marka ( already dmed @yangwao)

I send them this: https://subwork.xyz/membership.html#rent-venue-for-your-event

**Comment by yangwao** [comment]
Thanks!
They took 22/6 
Looking forward
