### ISSUE TITLE
Social media cards 

### ISSUE THREAD

**Issue by yangwao** [kodadot/subwork#32]
At least for first page having social media card would be nice! 

![image](https://github.com/kodadot/subwork/assets/5887929/2fe4e440-e722-4909-bb4b-4240beb568d2)

before looked like this
---
![image](https://github.com/kodadot/subwork/assets/5887929/c74bdbd9-5377-42f5-9c1d-f3543ff8d3cf)

**Comment by yangwao** [comment]
Related
- #65

**Comment by yangwao** [comment]
Maybe related?
- https://github.com/vuejs/vitepress/issues/504

**Comment by yangwao** [comment]
824f44e..3361567

**Comment by yangwao** [comment]
ookay with default it works somehow! :D 

![image](https://github.com/kodadot/subwork/assets/5887929/29d5eb91-d5a2-4209-9d78-efe1d054aaa5)

**Comment by yangwao** [comment]
d3652a5..6d52e9e

**Comment by yangwao** [comment]
https://www.opengraph.xyz/url/https%3A%2F%2Fwww.subwork.xyz%2Fhome.html

![image](https://github.com/kodadot/subwork/assets/5887929/3afa2342-d7fb-40fa-b2da-698d4eedce10)

Using this size of picture https://vitejs.dev/og-image-announcing-vite3.png

**Comment by yangwao** [comment]
> 1200:630 px
OG Image Size: The recommended size for an OG Image is 1.91:1. The recommended pixel dimensions of 1200:630 px (aspect ratio of 1.91:1).

**Comment by yangwao** [comment]
interesting 
- https://github.com/vuejs/vitepress/issues/551

**Comment by exezbcz** [comment]
![Frame 761](https://github.com/kodadot/subwork/assets/90852205/31c20116-2c47-4645-8b6d-3e9baef6cf6c)
![Frame 759](https://github.com/kodadot/subwork/assets/90852205/cc89121e-2665-49b1-b55f-83a75f895ec3)
![Frame 760](https://github.com/kodadot/subwork/assets/90852205/ef766b4a-4e76-461b-bbcd-0d4362ef39cd)

**Comment by exezbcz** [comment]
![Frame 762](https://github.com/kodadot/subwork/assets/90852205/6b9e93e8-4007-4acf-9c20-0a52251db2a3)

**Comment by exezbcz** [comment]
![Frame 763](https://github.com/kodadot/subwork/assets/90852205/2a6c11ef-b21c-4770-9b4a-ee891790c62c)

**Comment by yangwao** [comment]
![image](https://github.com/kodadot/subwork/assets/5887929/00d36140-c2de-45ae-840c-98ece5757f6f)
![image](https://github.com/kodadot/subwork/assets/5887929/d745e082-0b39-4c8f-b77b-07e2b5a9a68a)
![image](https://github.com/kodadot/subwork/assets/5887929/7b7f1766-7866-4aaa-ba75-96c35e083697)

**Comment by exezbcz** [comment]
![Frame 764](https://github.com/kodadot/subwork/assets/90852205/6fa5b71c-bd2c-431d-b60f-04a7a674df78)

**Comment by yangwao** [comment]
flexing in config 
8b2ea45..8a27c85

**Comment by yangwao** [comment]
looks like it works! 

![image](https://github.com/kodadot/subwork/assets/5887929/0c2e93b1-7754-427b-a652-7b87ae169a38)
