### ISSUE TITLE
discount for hotels/hostels

### ISSUE THREAD

**Issue by yangwao** [kodadot/subwork#5]
probably call around hotels in an accessible price range and get some referral for SubWork for people coming on regular basis and for longer stay (week?)

**Comment by poppyseedDev** [comment]
# Accommodation in Bled, Slovenia

## Hotels 🏨

Bled offers a wide range of hotels to cater for different budgets and preferences. Some notable options include:

1. [Grand Hotel Toplice](https://www.sava-hotels-resorts.com/en/sava-hoteli-bled/accommodations/grand-hotel-toplice): Located on the shore of Lake Bled, offering stunning views and luxurious accommodation.
2. [Hotel Park](https://www.sava-hotels-resorts.com/en/sava-hoteli-bled/accommodations/hotel-park): Known for its exceptional views of the lake, castle and Julian Alps.
3. [Hotel Jelovica](http://www.hoteljelovica.si/en/): Conveniently located in the heart of Bled, near the sports park and lake.

## Hostels 🛌

For budget-conscious travelers, hostels can be a great option. Here are a few in Bled:

1. [Hostel Bled](https://www.hostelworld.com/hosteldetails.php/Bled-Hostel/Bled/26392): Offering a mix of private rooms and dormitories.
2. [Castle Hostel 1004](https://www.hostelworld.com/hosteldetails.php/Castle-Hostel-1004/Bled/36856): Known for its friendly staff and clean rooms.
3. [Garden House Bled](https://www.hostelworld.com/hosteldetails.php/Garden-House-Bled/Bled/267299): Offers a unique and comfortable stay, with outdoor kitchen and fire pit.

## Airbnb Rentals 🏠

Airbnb can be a great option if you're looking for a home-away-from-home experience. Here are some links to get you started:

1. [Apartments in Bled](https://www.airbnb.com/Bled-Slovenia/homes?tab_id=home_tab&refinement_paths%5B%5D=%2Fhomes)
2. [Houses in Bled](https://www.airbnb.com/s/Bled--Slovenia/homes?property_type_id%5B%5D=2)
3. [Unique stays in Bled](https://www.airbnb.com/s/Bled--Slovenia/homes?property_type_id%5B%5D=12)

**Comment by poppyseedDev** [comment]
Provide affiliate links to the above links.
