### ISSUE TITLE
link aurora medium articles 

### ISSUE THREAD

**Issue by poppyseedDev** [kodadot/subwork#76]
https://medium.com/@poppyseedDev/do-standing-desks-actually-help-you-822ceb3d0c20
https://medium.com/@poppyseedDev/culture-at-subwork-%EF%B8%8F-593cdfa4f27f
https://medium.com/p/8c7bc648ee/edit

List where I will be adding articles:
https://medium.com/@poppyseedDev/list/subwork-the-ultimate-coworking-space-d65237ee2dce

**Comment by yangwao** [comment]
added in 09a6838
