### ISSUE TITLE
SubWork mini triathlon

### ISSUE THREAD

**Issue by yangwao** [kodadot/subwork#97]
coined by @poppyseedDev 

Swimming  - Vila Presern - Topice ~ 600m
Bike - around lake ~ 6.66km
Run uphill Straza ~ 1.5km and 150m ascent

https://connect.garmin.com/modern/activity/11376269002?share_unique_id=2

https://www.slovenia.info/en/things-to-do/events/5708-triathlon-bled-2023

(but links to 2022?)

![Screenshot_20230619_113032_Chrome.jpg](https://github.com/kodadot/subwork/assets/5887929/2ab633e0-631a-40d7-ab35-9ed4fbbf31bf)

What's Triathlon?
---
https://en.wikipedia.org/wiki/Triathlon?useskin=vector

X_x dead

**Comment by poppyseedDev** [comment]
https://connect.garmin.com/modern/activity/11398222571?share_unique_id=9

**Comment by yangwao** [comment]
241032c..03551b1
